version: "3"

networks:
  gitea_network:
    external: false
  guac_network:
    external: false

services:
  gitea:
    image: gitea/gitea:1.15.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea_network
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
       - "3000:3000"
       - "222:22"
    depends_on:
       - gitea_db
 
  gitea_db:
     image: mysql:8
     container_name: gitea_db
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=gitea
       - MYSQL_USER=gitea
       - MYSQL_PASSWORD=gitea
       - MYSQL_DATABASE=gitea
     networks:
       - gitea_network
     volumes:
       - ./data/gitea_db:/var/lib/mysql

  guacd:
    image: guacamole/guacd
    container_name: guacd_compose
    networks:
      - guac_network
    restart: always
    volumes:
    - ./data/guacd/drive:/drive:rw
    - ./data/guacd/record:/record:rw

  postgres:
    image: postgres
    container_name: guac_db
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: guacamole_user
      POSTGRES_USER: guacamole_user
    networks:
      - guac_network
    restart: always
    volumes:
    - ./temp:/docker-entrypoint-initdb.d:ro
    - ./data/guac_db:/var/lib/postgresql/data:rw

  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: guacamole_user
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
      - guacd
    networks:
      - guac_network
    ports:
      - 8080:8080/tcp
    restart: always
