# image
# container name
# environment  
# volumes
# network
# port
# depends_on
# links
# restart

version: "3"

networks:
  gitea_network:
    external: false
  guac_network:
    external: false
  semaphore_network:
    external: false

services:
  gitea:
    image: gitea/gitea:1.15.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea_db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea_network
    ports:
       - "3000:3000"
       - "222:22"
    depends_on:
       - gitea_db
    restart: always

 
  gitea_db:
     image: mysql:8
     container_name: gitea_db
     environment:
       - MYSQL_ROOT_PASSWORD=gitea
       - MYSQL_USER=gitea
       - MYSQL_PASSWORD=gitea
       - MYSQL_DATABASE=gitea
     volumes:
       - ./data/gitea_db:/var/lib/mysql
     networks:
       - gitea_network
     restart: always

  guacd:
    image: guacamole/guacd
    container_name: guacd_compose
    volumes:
      - ./data/guacd/drive:/drive:rw
      - ./data/guacd/record:/record:rw
    networks:
      - guac_network
    restart: always

  guac_db:
    image: postgres
    container_name: guac_db
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: guacamole_user
      POSTGRES_USER: guacamole_user
    volumes:
      - ./temp:/docker-entrypoint-initdb.d:ro
      - ./data/guac_db:/var/lib/postgresql/data:rw
    networks:
      - guac_network
    restart: always

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: guac_db
      POSTGRES_PASSWORD: guacamole_user
      POSTGRES_USER: guacamole_user
    networks:
      - guac_network
    ports:
      - 8080:8080/tcp
    depends_on:
      - guacd
      - guac_db
    links:
      - guacd
    restart: always

  semaphore:
    image: playniuniu/ansible-semaphore
    container_name: sempahore
    volumes:
      - ./data/semaphore:/data
    networks:
      - semaphore_network
    ports:
      - 4000:3000
    depends_on:
      - semaphore_db
    restart: always

  gogs:
    image: gogs/gogs
    container_name: gogs
    volumes:
      - ./data/gogs:/data
    networks:
      - semaphore_network
    ports:
      - 3000:3000
      - 2222:22
    depends_on:
      - semaphore_db
    restart: always

  semaphore_db:
    image: mariadb
    container_name: semaphore_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/semaphore_db:/var/lib/mysql
    networks:
      - semaphore_network
    ports:
      - 3306:3306
    restart: always
