# image
# container name
# environment
# volumes
# network
# port
# depends_on
# links
# restart

version: "3"

networks:
  gitea_network:
    external: false
  semaphore_network:
    external: false

services:

  gitea:
    image: gitea/gitea:1.15.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea_db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${gitea_user}
      - GITEA__database__PASSWD=${gitea_password}
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__IMPORT_LOCAL_PATHS=true
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea_network
    ports:
      - "${gitea_port}:${gitea_port}"
    depends_on:
       - gitea_db
    restart: always

  gitea_db:
     image: mysql:8
     container_name: gitea_db
     environment:
       - MYSQL_ROOT_PASSWORD=${gitea_db_root_password}
       - MYSQL_USER=${gitea_user}
       - MYSQL_PASSWORD=${gitea_password}
       - MYSQL_DATABASE=gitea
     volumes:
       - ./data/gitea_db:/var/lib/mysql
     networks:
       - gitea_network
     ports:
       - "${gitea_db_port}:3306"
     restart: always

  semaphore:
    image: semaphore
    build: ./images/semaphore/
    container_name: semaphore
    environment:
      - SEMAPHORE_DB_USER=${semaphore_db_user}
      - SEMAPHORE_DB_PASS=${semaphore_db_password}
      - SEMAPHORE_DB_HOST=semaphore_db
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/data/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=${semaphore_admin_password}
      - SEMAPHORE_ADMIN_NAME=${semaphore_admin_name}
      - SEMAPHORE_ADMIN_EMAIL=admin@localhost
      - SEMAPHORE_ADMIN=admin
      - ANSIBLE_HOST_KEY_CHECKING=False
    volumes:
      - ./data/semaphore:/data
    networks:
      - semaphore_network
    ports:
      - "${semaphore_port}:3000"
    depends_on:
      - semaphore_db
    restart: always

  semaphore_db:
    image: mysql:5.6
    container_name: semaphore_db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: ${semaphore_db_user}
      MYSQL_PASSWORD: ${semaphore_db_password}
    volumes:
      - ./data/semaphore_db:/var/lib/mysql
    networks:
      - semaphore_network
    ports:
      - "${semaphore_db_port}:${semaphore_db_port}"
